# Install some basic required packages and standard config
---
- hosts: raspberry-cam
  become: yes
  gather_facts: yes
  vars:
    boot_config_options:
      # Set the GPU memory split value. 128 is the minimum for the camera
      - regexp: "^#?gpu_mem"
        line: "gpu_mem=128"

      # Enable the Camera interface
      - regexp: "^#?start_x"
        line: "start_x=1"

      # Disable the Camera LED, "0" is enabled, "1" is disabled
      - regexp: "^#?disable_camera_led"
        line: "disable_camera_led=0"

  tasks:
    # Run apt-get update and apt-get upgrade, install aditional packages
    - name: Update apt packages
      become: yes
      apt:
          update_cache=yes

    # Upgrade apt packages
    - name: Upgrade apt packages
      become: yes
      apt:
          upgrade=dist

    - name: Install dependancies from apt
      become: yes
      apt: name={{item}} state=installed
      with_items:
        - ufw
